---
version: '3'
volumes:
  db-data:
    external: false
services:
  dev:
    environment:
      dbUrl: mongodb://admin:admin@deploy_counts-mongo-1/stats_development?authSource=admin
    build:
      context: '.'
      dockerfile: 'Dockerfile'

    command: 'tail -f /dev/null'
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - '.:/var/service:cached'
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: stats
    volumes:
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./docker/mongod.conf:/etc/mongod.conf:ro
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
