name: CI

on:
  push:

env:
  NODE_VERSION: v18.14.0
  YARN_VERSION: 4.0.2

jobs:
  build:
    name: Setup Instance
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - id: corepack-enable
        run: corepack enable

      - id: corepack-prepare
        run: corepack prepare yarn@${{ env.YARN_VERSION }} --activate

      - id: yarn-set-version
        run: yarn set version ${{ env.YARN_VERSION }}

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: yarn install --immutable

  lint:
    name: Lint
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Lint Code
        run: yarn run lint

  test:
    name: Test
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Lint Code
        run: yarn test
